### ISSUE TITLE
Unable to parse value 'Highest'

### ISSUE THREAD

**Issue by raygerrard** [spatools/grunt-nuget#13]
When including a package in the packages.config with the version with a value of "Highest" you get the following error:

Error: Unable to parse version value `Highest` from `packages.config`

**Comment by SomaticIT** [comment]
Hello,
Sorry for my delayed response.
I think your are doing this thing not in the good place.
Take a look at : http://docs.nuget.org/release-notes/nuget-2.8#dependencyversion-attribute.
