### ISSUE TITLE
Failed to load msbuild Toolset

### ISSUE THREAD

**Issue by abjerner** [spatools/grunt-nuget#16]
I can't find anywhere mentioning this error, so here goes - in both `v0.1.7` and `v0.2.0`, I'm receiving this error when running `nugetpack`:

```
Running "nugetpack:dist" (nugetpack) task
Trying to create NuGet package from src/Skybrud.Umbraco.Redirects/Skybrud.Umbraco.Redirects.csproj.
ERROR
>> Error: Failed to load msbuild Toolset
>>   Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Warning: Task "nugetpack:dist" failed. Use --force to continue.

Aborted due to warnings.
```

The same configuration works fine with `v0.1.6`. I can see that `nuget.exe` was updated - does the updated exe require something else to be installed?

My `Gruntfile.js` and `package.json` can be found here:

https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/e515d6f7e649adcf92e74fd339550312153ffb7c/Gruntfile.js#L72
https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/e515d6f7e649adcf92e74fd339550312153ffb7c/package.json

Thanks in advance ;)

**Comment by SomaticIT** [comment]
MSBuild version 14 is provided with Visual Studio 2015.
You can customize the target MSBuild version using the `msbuildversion` option.

The `msbuildversion` option accepts the following values : `4`, `12`, `14`.
Try to adujst this settings in your configuration to match your configuration.

**Comment by abjerner** [comment]
Thanks for the answer :D

But I'm not entirely sure why MSBuild is required? Shouldn't NuGet.exe simply pack an already build DLL?

**Comment by SomaticIT** [comment]
It is mandatory for some packages which need to be built during installation.
I think NuGet does not provide a packaged MSBuild DLL because it's a separate program with a lot of dependencies and there are multiple version of MSBuild depending on your project.

**Comment by jmbeach** [comment]
What about for restore?
