### ISSUE TITLE
NuGet v3.4.3 does not acknowledge Msbuildversion flag

### ISSUE THREAD

**Issue by jmbeach** [spatools/grunt-nuget#17]
I was very confused that nuget was looking for Msbuild tools version 14 and wouldn't change even if I specified:

```
options: {
			msbuildversion: 4
		}
```

Then I tested `.\node_modules\grunt-nuget\libs\nuget.exe restore .\mysolution.sln -MSBuildVersion 4 -packagesdirectory 'packages'` and saw it was giving the same error. It doesn't have the option available apparently. I fixed the issue by going back to the 0.1.5 release of grunt-nuget. I would recommend updating to nuget 4 soon

**Comment by jmbeach** [comment]
Error is same as #16

**Comment by SomaticIT** [comment]
I will upgrade NuGet to 4.0 as soon as it get released.
Are we sure this option will be supported in 4.0 release ?

**Comment by jmbeach** [comment]
I'm not actually. What's odd is that when you run the nuget help for the restore command for version 3, it tells you it's supported, but it completely ignores it.

**Comment by SomaticIT** [comment]
The latest release `0.3.0` has been released and contains `NuGet.exe` in version `4.1.0`.
You can upgrade your local installation.
