### ISSUE TITLE
nugetrestore does not work on VS2017

### ISSUE THREAD

**Issue by mariusandersen** [spatools/grunt-nuget#18]
Using 0.2.0 of grunt-nuget you get this error when running "grunt nugetrestore":
ERROR
>> Error: Failed to load msbuild Toolset
>>   Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Warning: Task "nugetrestore:restore" failed. Use --force to continue.

Aborted due to warnings.

Updated to officially released nuget 4.0 and it worked flawlessly. Please update nuget.exe version.

**Comment by SomaticIT** [comment]
I updated `NuGet.exe` to version `4.1.0` in `grunt-nuget` NPM release `0.3.0`.
You can update your local installation.
