### ISSUE TITLE
Support for VS2017 /.net core csproj projects

### ISSUE THREAD

**Issue by sherland** [spatools/grunt-nuget#19]
The current "active" release is 0.1.4 at https://github.com/spatools/grunt-nuget/releases.
At https://www.npmjs.com/package/grunt-nuget the release-history includes newer release's, but not the (currently) latest v0.3.0.

I have installed grunt-nuget 0.2.0 and manually updated nuget.exe to 4.1 in the lib folder. After this my projects build as expected. :-)
Do you expect to do a release of 0.3.0 to npmjs soon so that I can test this on my build-machines?

**Comment by SomaticIT** [comment]
The active __Github__ release is `0.1.4` but the last __git__ tag release is `0.3.0`.
If you install grunt-nuget from NPM, you will install the latest version `0.3.0`:

```bash
$ npm install grunt-nuget --save-dev
```

**Comment by sherland** [comment]
Hi, just tried now, and it's working as you say. The thing that confused me was that https://www.npmjs.com/package/grunt-nuget don't refer to that version, but that is just a minor issue. Thanks a lot!
