### ISSUE TITLE
Support Nuget update command

### ISSUE THREAD

**Issue by bbaia** [spatools/grunt-nuget#2]
It will be great to allow to update `NuGet.exe` file from a task (`nuget update -self`).

Options:
- A 'safe' property to allow `nuget update -safe`

**Comment by SomaticIT** [comment]
`grunt-nuget` provides `nugetupdate` task in version `0.2+`.

*Warning it only works with solution files*
You can see details in wiki: https://github.com/spatools/grunt-nuget/wiki/Update-Options.

Thanks.
