### ISSUE TITLE
Update nuget.exe from 4.1 to 4.6.2

### ISSUE THREAD

**Issue by sherland** [spatools/grunt-nuget#21]
Latest and recommended version of nuget.exe at https://www.nuget.org/downloads is 4.6.2. 

There are multiple issues fixed in that version. I'm currently hit by this: https://scottsauber.com/2017/08/22/fix-for-package-microsoft-aspnetcore-2-0-0-is-not-compatible-with-netcoreapp2-0/

**Comment by SomaticIT** [comment]
Sorry for my lack of time.
I published a new update (`v0.3.1`) in which I upgraded NuGet to version `v4.7.1`.
Thank you for your request.
